### ISSUE TITLE
Data not updated when the schedule is changed

### ISSUE THREAD

**Issue by juppe1969** [xmltv-se/issues#15]
svt2.svt.se, svt1.svt.se

2020-03-15

The data for svt2 at 12.15 is wrong, it says that it is Ishockey sm-finaler, but it is Ballets suédois.
Seams like the files are not updated when they once have been created.

I think this is on every channel that change their program after the creation of the file the first time, but I'm not sure.

**Comment by jnylen** [comment]
Hi,
I have had some issues when I changed the configuration handler, that should be fine now. Data gets updated after each update has been received from the channel. But only then.

SVT sends updated files every day by ftp. I'll check if they have uploaded any recently.
And if there is any files that have been missed due to the issues.

I'm working to keep these as automatic as possible which was not the state with nonametv.

You can check Vind out in the org if you wanna help 👍

I'll post a comment when I know.

Email and ftp channels gets updated instantly.
Web gets updated in a specific schedule for that channel

**Comment by jnylen** [comment]
Should be in by now.

**Comment by juppe1969** [comment]
I dont know what you mean by "You can check Vind out in the org if you wanna help"
But if I would know I would like to help.
