### ISSUE TITLE
Godare

### ISSUE THREAD

**Issue by anders55j** [xmltv-se/issues#18]
**NOTE: That we do one issue per channel. If you want to request multiple please create one issue per channel.**

**Channel Name**

Godare

**Available countries**

Sweden

**URL**

https://godare.se/

**Contact email / Press URL**
karin.widmark@schibsted.com is on the homepage. Godare seems to be a sibling to matkanalen.tv.

**Comment by jnylen** [comment]
@anders55j we do get the data from them already since a few weeks back. I just haven't had the time to create an importer. If you want to I can send you the file and you  can do a PR on [xmltv-se/vind](https://github.com/xmltv-se/vind).

I expect to be able to do it in a few weeks. But no promises. The world is too busy right now.

**Comment by anders55j** [comment]
Thanks for the offer, but it is not in a language I'm familiar with,
