### ISSUE TITLE
Limit the free data to 3 days

### ISSUE THREAD

**Issue by jnylen** [xmltv-se/issues#21]
We are going to limit the data supplied by xmltv.se to 3 days so we can most companies from abusing the data to resell it. We have been getting hit on our API (using our own site api key) and on XMLTV.se by companies and while we have been able to ban some we can't ban every ip.

We are going to limit all channels to have 3 days (today + 2 days) in an upcoming deployment.

**Comment by anders55j** [comment]
Sad news, but thanks for the heads-up.

**Comment by rco133** [comment]
Very sad indeed.

Why must some people ruin it for everyone else just to make som money :-(

Any idea how to get the data now? Have tried to click on the link for Honeybee.it, but it just tells me that it doesn't exist.

Any info will be most appreciated since 2 days of data, will make it troublesome to create timers for recordings and such things.

**Comment by jnylen** [comment]
This will happen in a few months.
I'm also coming up with alternative ways of handling this aswell. As requiring people to sign up for an account to get the data so we know whether people steal it or not.

That would allow me to bump the days to a week or so.

**Comment by rco133** [comment]
Thanks for the info.

A week would be fine I gues. Just not sure how to get the data. I would also not mind to pay the 149,- SEK a year for the Honeybee service. But I have no idea how to get the data into the programs I use, since they depend on running xmltv from within the program.

Time will tell. Anyway, thanks for the info and providing the data. Just sad that some people misuse it.

**Comment by jnylen** [comment]
This is now in.
