### ISSUE TITLE
Times are 2 hours off on comedycentral.tv

### ISSUE THREAD

**Issue by Neoand2** [xmltv-se/issues#28]
Times are 2 hours off for all shows on comedycentral.tv . 
Maybe a timezone problem?

For example, "The Daily Show" start ="20200528191000 +0000" should be either 
"20200528171000 +0000" or
"20200528191000 +0200"

The show starts at 19:10 CEST

**Comment by jnylen** [comment]
@Neoand2 yeah, the library we use for parsing some formats changed from automatically converting it to utc from default true to false.

Which messed it up for some sources. I changed this back to true.

I'll push this live later today so if it isn't fixed in two days just ping me in here and i'll look into it.

**Comment by Neoand2** [comment]
@jnylen thank you.. works fine now
