### ISSUE TITLE
TV Guide channels (honeybee.it ) do not reflect selection of channels

### ISSUE THREAD

**Issue by pju55** [xmltv-se/issues#33]
Hi Joakim,
Some time ago (May 14th) I sent a mail to "support@honeybee.it" because the guide found on for instance "https://honeybee.it/tvguide/2020-07-05" does not reflect my selection and has not done so for several months.

I also have sent questions regarding how to renew my VIP subscription - also without reponse.
Seems like mails does not get to you - or just too busy...?
Can see on the issue tracker that you've been busy for a long time.

Fine with me, no problem. Just for the future would like to know if I in should abandon mails and open an issue...
Best regards 
Poul

**Comment by jnylen** [comment]
@pju55 I remember answering the renewal email. Not remembering any tvguide email.
I'll fix that this week.

Honeybee questions should be sent to that email, it's just forwarded to my company email. If I don't answer within a week you can just email my private email.

You can go ahead and ping me from the emails you sent and i'll answer from them.

**Comment by pju55** [comment]
Hi Joakim,

Yes, it's correct that you answered a renewal mail.
But I have not seen any answer to my follow-up mail - if the only way to
change creditcard  is cancel/recreate the subscription when it runs out.
Most likely a stupid question - but I have had enough trouble on other
sites to make me a bit unsafe..

Best regards
Poul

Den søn. 5. jul. 2020 kl. 17.27 skrev Joakim Nylén <notifications@github.com

**Comment by jnylen** [comment]
Hi Poul,
We are using Mollie for payments which doesn't really use the same system as Stripe. Meaning the payments happen on their payment site.

And currently I haven't added a way to change the payment method as their way of handling it is a bit messy. We need to create a mandate in order to be allowed to charge that method. And the way they handle subscriptions is that if the first charge doesn't work (I.e. No money on the card) then they won't recharge it. But they won't cancel the subscription for some reason.

So we have had to add a checks for that. Adding a change card system to that might seem innocent but it will probably break something.

Currently the only way to change the card is when the subscription fails the be renewed. A week before the end date. You'll get an email when that happens. 

As I'm having a month of vacation until I'm back at work I'm going through alot of issues and fixing most of them. Currently I have major ones planned such as:
- Complete move over to Elixir from Ruby. Currently only the export is run in Elixir. And it seems to work fine currently. No major memory issues the ruby variant had. Most things are already done. Only the payment system is missing.
- Fix some Vind stuff to future proof it. Such as moving the config from static json files to the database so we don't have to update the files and restart it everytime we have to change something. This is probably an easy fix 🤞
- Finish up the MVP of Metagraph, our open-source public domain database for movies, television shows... Basically anything.
- Move servers from VPSes to managed services on Heroku or something similar so we don't have to worry about backups etc.

So I'm working hard to fix most stuff. Before I'm back at work as I usually get busy there.

**Comment by pju55** [comment]
Hi Joakim,

Thanks a lot for your answer and thorough explanations - I'll just wait for
the mail.

Seems like you've got enough to do in your vacation - hopefully it's OK for
you to use the days off on this.
Fascinated thinking back on the days when I started in IT. Only a (big)
handful of programming languages available. And none of them very helpful.
And the same for databases.
Today lots of languages available with a magnitude of more support to the
programmer - but also with the needs and pitfalls of choosing the right one
for the particular job.

Any way, have a nice summer - really appreciate your efforts to make a good
product even better!
Best regards Poul

Den søn. 5. jul. 2020 kl. 18.58 skrev Joakim Nylén <notifications@github.com
