### ISSUE TITLE
[CR] TV - TNT Comedy

### ISSUE THREAD

**Issue by reloxx13** [xmltv-se/issues#36]
**NOTE: That we do one issue per channel. If you want to request multiple please create one issue per channel.**

**Channel Name**
TNT Comedy
Note: There r more missing TNT Channels.

**Available countries**
Europe? German

**URL**
https://tnt-tv.de/tnt-comedy/

**Contact email / Press URL**

https://tnt-tv.de/impressum

**Comment by jnylen** [comment]
Won't be added due to Turner stopped delivering them to me and only deliver them to TV providers so unless I get a customer that are a direct customer of turner then I won't be able to provide any of the Turner channels.

If you can poke your local office of turner to get em access go ahead. But I have tried since we lost the access in like 2017 to get it back but no response.

If I get access back I'll get it back asap. But until then I can't.
