### ISSUE TITLE
Missing update of honeybee xml file.

### ISSUE THREAD

**Issue by pju55** [xmltv-se/issues#37]
Seems to be a problem with my honeybee.xml update.
On my "https://honeybee.it/xmltv/edit" page I can see "EXPORTED 8 DAYS AGO"
Which matches the timestamp of the downloaded xml-file which is dated "Jul 30 08:16".

Best regards 
Poul

**Comment by jnylen** [comment]
@pju55 I got another report for that to my email, and it should be fixed now, running yours manually soon.

JFYI: This issue page is only for XMLTV.se related stuff, not honeybee.it. I.e. if you want a channel added, complete missing data (you need to check xmltv.se for that, otherwise it should be reported to the support email).

Or you can just do everything through the support email.

**Comment by pju55** [comment]
@jnylen Yes, looking much better now.
I know this is not the place for honeybee problems. But, I have a long record of sending mails to the support email without getting response - seems a bit like a spam filter eats my mails. But next time, I'll try the mail again :-)
Have a nice day.
Poul
